### teste de buscar todos os Sala de Aulas
GET http://localhost:40000/getAllSalasDeAula HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF3ZSIsImlhdCI6MTY5Mjc5ODg2MSwiZXhwIjoxNjkyNzk5NDYxfQ.43OGaDLf0iQHUXgfM8wBETYE5A8TGHR1G0hfupccsfM

{    
    
}

### Buscar Sala de Aula por ID
POST http://localhost:40000/getSalasDeAulaByID HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF3ZSIsImlhdCI6MTY5MzM5NzE3OCwiZXhwIjoxNjkzMzk3Nzc4fQ.EezpOMc_2UOvUb0ujlgJ1Tp9dlcg0Wkz_q8kixdxa6E

{    
    "saladeaulaid": 1
}

### Insert de Sala de Aula 
POST http://localhost:40000/insertSalasDeAula HTTP/1.1 
content-type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF3ZSIsImlhdCI6MTY5MzM5NzE3OCwiZXhwIjoxNjkzMzk3Nzc4fQ.EezpOMc_2UOvUb0ujlgJ1Tp9dlcg0Wkz_q8kixdxa6E

{
"saladeaulaid": 3, 
"descricao": "Sala de Computadores", 
"localizacao": "Bloco G", 
"capacidade": "50", 
"removido":false,
}

### Update de Sala de Aula 
POST http://localhost:40000/updateSalasDeAula HTTP/1.1 
content-type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF3ZSIsImlhdCI6MTY5MzM5NzE3OCwiZXhwIjoxNjkzMzk3Nzc4fQ.EezpOMc_2UOvUb0ujlgJ1Tp9dlcg0Wkz_q8kixdxa6E

{
"saladeaulaid": 3, 
"descricao": "Sala de Computadores Quanticos", 
"localizacao": "Bloco F", 
"capacidade": "60", 
"removido":false,
}

### Delete de Sala de Aula 
POST http://localhost:40000/DeleteSalasDeAula HTTP/1.1 
content-type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF3ZSIsImlhdCI6MTY5MTQ5MDg3NCwiZXhwIjoxNjkxNDkxNDc0fQ.1ABhMgWYm8gGKy7q90GOPQpNoY5M1LLzpCltKxFjcEo

{
"saladeaulaid": 1
}
